# Generated by Django 5.2.1 on 2025-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New Driver'), ('INFO_CHANGE', 'Information Change')], max_length=20)),
                ('id_document', models.FileField(upload_to='drivers/id_documents/')),
                ('car_info_document', models.FileField(upload_to='drivers/car_info/')),
                ('car_video', models.FileField(upload_to='drivers/car_videos/')),
                ('personal_photo', models.ImageField(upload_to='drivers/personal_photos/')),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='drivers/additional_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
